apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: "pod-1"
spec:
  selector:
    matchLabels: 
      app: "my-app"
  template:
    metadata:
      name: "my-app-pod"
      labels:
        app: "my-app"
    spec:
      containers:
      - name: "container-1"
        image: "sawany/backend"
