on:
  push:
    branches: ["actions-v1"]
    paths: 
      - "backend/*"
      - ".github/*"
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: build backend
        working-directory: ./backend
        run: go build .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        with: 
          python-version: '3.12'
      - name:
        working-directory: ./testing
        run: |
          make run
